before_script:
  - pip install tox
py34:
  image: python:3.4-alpine
  stage: test
  script: 
    - tox -e py34,flake8
py35:
  image: python:3.5-alpine
  stage: test
  script: 
    - tox -e py35,flake8
py36:
  image: python:3.6-alpine
  stage: test
  script: 
    - tox -e py36,flake8
py37:
  image: python:3.7-alpine
  stage: test
  script: 
    - tox -e py37,flake8
  
